# Generated by Django 5.0.6 on 2024-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('school', '0002_alter_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='students',
            field=models.ManyToManyField(blank=True, to='school.student'),
        ),
    ]
